import type { Platform, GradientPreset, PlatformPreset } from '@/types';

export const PLATFORM_GRADIENTS: Record<Platform, GradientPreset[]> = {
  instagram: [
    {
      id: 'ig-golden-hour',
      name: 'Golden Hour',
      colors: ['#f9a825', '#e91e8c', '#9c27b0'],
      direction: '135deg',
    },
    {
      id: 'ig-sunset',
      name: 'Sunset Glow',
      colors: ['#ff6b6b', '#feca57', '#ff9ff3'],
      direction: '135deg',
    },
    {
      id: 'ig-rose',
      name: 'Rose Dawn',
      colors: ['#ee0979', '#ff6a00'],
      direction: '135deg',
    },
  ],
  twitter: [
    {
      id: 'tw-dark-mode',
      name: 'Dark Mode',
      colors: ['#0f1923', '#1a2a3a'],
      direction: '135deg',
    },
    {
      id: 'tw-midnight',
      name: 'Midnight',
      colors: ['#000000', '#0d1b2e'],
      direction: '135deg',
    },
    {
      id: 'tw-blue',
      name: 'Twitter Blue',
      colors: ['#1da1f2', '#0d7bc4'],
      direction: '135deg',
    },
  ],
  tiktok: [
    {
      id: 'tt-viral',
      name: 'Viral Clip',
      colors: ['#010101', '#69c9d0', '#ee1d52'],
      direction: '135deg',
    },
    {
      id: 'tt-neon',
      name: 'Neon Night',
      colors: ['#0a0a0a', '#ff006e', '#8338ec'],
      direction: '135deg',
    },
    {
      id: 'tt-hot',
      name: 'Hot Pink',
      colors: ['#1a1a2e', '#16213e', '#e94560'],
      direction: '135deg',
    },
  ],
  youtube: [
    {
      id: 'yt-studio',
      name: 'Studio',
      colors: ['#0f0f0f', '#282828'],
      direction: '135deg',
    },
    {
      id: 'yt-crimson',
      name: 'Crimson Stage',
      colors: ['#1a0000', '#ff0000'],
      direction: '135deg',
    },
    {
      id: 'yt-dark-red',
      name: 'Dark Red',
      colors: ['#0d0d0d', '#3d0000'],
      direction: '135deg',
    },
  ],
  linkedin: [
    {
      id: 'li-pro',
      name: 'Professional',
      colors: ['#0a66c2', '#064499'],
      direction: '135deg',
    },
    {
      id: 'li-navy',
      name: 'Navy Corporate',
      colors: ['#0d1b3e', '#1a3a6e'],
      direction: '135deg',
    },
    {
      id: 'li-clean',
      name: 'Clean White',
      colors: ['#f3f6f9', '#e8edf2'],
      direction: '135deg',
    },
  ],
  facebook: [
    {
      id: 'fb-highlight',
      name: 'Highlight',
      colors: ['#1877f2', '#1a6ae0'],
      direction: '135deg',
    },
    {
      id: 'fb-friendly',
      name: 'Friendly Blue',
      colors: ['#3b5998', '#8b9dc3'],
      direction: '135deg',
    },
    {
      id: 'fb-social',
      name: 'Social Warm',
      colors: ['#1877f2', '#42a5f5'],
      direction: '135deg',
    },
  ],
  unknown: [
    {
      id: 'default-dark',
      name: 'Deep Space',
      colors: ['#0f0c29', '#302b63', '#24243e'],
      direction: '135deg',
    },
    {
      id: 'default-aurora',
      name: 'Aurora',
      colors: ['#00c6ff', '#0072ff'],
      direction: '135deg',
    },
    {
      id: 'default-emerald',
      name: 'Emerald',
      colors: ['#0f2027', '#203a43', '#2c5364'],
      direction: '135deg',
    },
  ],
};

export const PLATFORM_PRESETS: PlatformPreset[] = [
  {
    id: 'instagram-golden',
    name: 'Golden Hour',
    platform: 'instagram',
    vibe: 'Warm amber gradient, serif font',
    gradient: PLATFORM_GRADIENTS.instagram[0],
    font: 'Playfair Display',
    textColor: '#ffffff',
    borderRadius: 24,
    shadowIntensity: 60,
  },
  {
    id: 'twitter-dark',
    name: 'Dark Mode',
    platform: 'twitter',
    vibe: 'Near-black bg, white text, minimal',
    gradient: PLATFORM_GRADIENTS.twitter[0],
    font: 'Inter',
    textColor: '#ffffff',
    borderRadius: 16,
    shadowIntensity: 40,
  },
  {
    id: 'tiktok-viral',
    name: 'Viral Clip',
    platform: 'tiktok',
    vibe: 'Hot pink/black gradient, bold font',
    gradient: PLATFORM_GRADIENTS.tiktok[0],
    font: 'Outfit',
    textColor: '#ffffff',
    borderRadius: 20,
    shadowIntensity: 80,
  },
  {
    id: 'youtube-studio',
    name: 'Studio',
    platform: 'youtube',
    vibe: 'Deep red accent, dark bg, clean',
    gradient: PLATFORM_GRADIENTS.youtube[0],
    font: 'Roboto',
    textColor: '#ffffff',
    borderRadius: 12,
    shadowIntensity: 50,
  },
  {
    id: 'linkedin-pro',
    name: 'Professional',
    platform: 'linkedin',
    vibe: 'Navy/white, corporate clean',
    gradient: PLATFORM_GRADIENTS.linkedin[0],
    font: 'Inter',
    textColor: '#ffffff',
    borderRadius: 8,
    shadowIntensity: 30,
  },
  {
    id: 'facebook-highlight',
    name: 'Highlight',
    platform: 'facebook',
    vibe: 'Blue gradient, rounded, friendly',
    gradient: PLATFORM_GRADIENTS.facebook[0],
    font: 'Nunito',
    textColor: '#ffffff',
    borderRadius: 28,
    shadowIntensity: 45,
  },
];

export const GOOGLE_FONTS = [
  'Inter',
  'Roboto',
  'Outfit',
  'Playfair Display',
  'Nunito',
  'Poppins',
  'Montserrat',
  'Lato',
  'Open Sans',
  'Raleway',
  'DM Sans',
  'Space Grotesk',
  'Sora',
  'Plus Jakarta Sans',
  'Archivo',
  'Bricolage Grotesque',
  'Bebas Neue',
  'Josefin Sans',
  'Cinzel',
  'Dancing Script',
];
